# Generated by Django 4.1.7 on 2023-05-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('published', models.IntegerField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('coverMusic', models.ImageField(upload_to='music/')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('1', 'User'), ('2', 'Admin')], max_length=1)),
                ('coverPlaylist', models.ImageField(upload_to='playlist/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('1', 'User'), ('2', 'Admin')], default='1', max_length=1)),
                ('avatarImg', models.ImageField(upload_to='user/')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdufyStarter.playlist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdufyStarter.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdufyStarter.music')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdufyStarter.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdufyStarter.music')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdufyStarter.user')),
            ],
        ),
    ]
