# Generated by Django 4.1.7 on 2023-05-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdufyStarter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdufyStarter.music')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdufyStarter.user')),
            ],
        ),
    ]
